name       : brackets
version    : 1.14
release    : 16
source     :
    - https://github.com/adobe/brackets/releases/download/release-1.14/Brackets.Release.1.14.64-bit.deb : 4df8490efb8a35ff93ac6975655ab4af9a56547eb4a346514803aa2e1f20f30e
license    : MIT
component  : programming.ide
summary    : Brackets is a modern open-source code editor
description: |
    Brackets is a modern open-source code editor
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(xcomposite)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - cups-devel
rundeps    :
    - nodejs
setup      : |
    ar x $sources/Brackets.Release.${version}.64-bit.deb
    tar xf data.tar.xz
    sed -i 's:/opt/brackets/::g' opt/brackets/brackets.desktop
    rm -r usr/bin
install    : |
    install -dm00755 $installdir/usr/bin
    install -Dm00755 opt/brackets/brackets.desktop $installdir/usr/share/applications/brackets.desktop
    mv opt/brackets $installdir/usr/share/
    ln -s /usr/share/brackets/brackets $installdir/usr/bin/brackets
    rm $installdir/usr/share/brackets/brackets.desktop
